### ISSUE TITLE
Change user's email before sending request

### ISSUE THREAD

**Issue by virtual89** [florianheinemann/passwordless#101]
Hi! 
Is it any possibility to change email address in `requestToken` before sending it to user ?
I have record with the email in the database, however there are 2 emails for each  user (1t and 2nd). I want to change the email to a specific one (let's choose 2nd) even if the user typed  1st. 
As far as I understand request Token rely on the check of presence or absence of the email in the DB. Event if I try to change email address in `callback` function it still uses the initial one from the `req.body`. 

Then I tried this, and it didn't work ether: 
```
router.post('/sendToken', function (req,res) {
    //validation here
    let db_an = checkEmailInDB(req.body['user']);
    db_an.then((address) =>{
        req.body = {"user": address};
        console.log(req.body);
        res.send(req.body);
        passwordless.requestToken(
		function(user, delivery, callback) {
			callback(null, user);
		})
    });
});
```
Seems like `passwordless.requestToken`in this case is never called. Probably because it should act as middleware.

**Comment by virtual89** [comment]
Eventually did it like that for now. Not sure if this is right or wrong (in terms of following use with the passwordless). Would appreciate if you can comment on that. 

```
router.post('/sentToken', function (req,res) {
    //validation of input
    let db_an = checkEmailinDB(req.body['user']);
    db_an.then((address) =>{
        let token = (passwordless._generateToken())();
        passwordless._tokenStore.storeOrUpdate(token, address,ttl,null, function(storeError){
            if(storeError) {
                throw (new Error('Error on the storage layer: ' + storeError));
            } else {
                passwordless._defaultDelivery.sendToken(token, address, address, function(deliveryError){
                    if(deliveryError) {
                        throw (new Error('Error on the deliveryMethod delivery layer: ' + deliveryError));
                    }
                })
            }

        })
    });
});
```

**Comment by florianheinemann** [comment]
Hi,
sorry for the late reply. That seems unnecessarily complicated to me :)

I'd probably just amend the `addDelivery()` call, e.g.:
```javascript
passwordless.addDelivery(
    function(tokenToSend, uidToSend, recipient, callback) {
        // This to be added - rest of function remains unchanged
        recipient = turnEmailIntoPrimaryEmail(recipient); 

        var host = 'localhost:3000';
        smtpServer.send({
            text:    'Hello!\nAccess your account here: http://' 
            + host + '?token=' + tokenToSend + '&uid=' 
            + encodeURIComponent(uidToSend), 
            from:    yourEmail, 
            to:      recipient,
            subject: 'Token for ' + host
        }, function(err, message) { 
            if(err) {
                console.log(err);
            }
            callback(err);
        });
});
```

Then you can implement `turnEmailIntoPrimaryEmail` so suit your needs. Probably would want to make it async

Cheers

**Comment by virtual89** [comment]
> I'd probably just amend the addDelivery() call, e.g.:

You're right ))) 
Thanks !
