### ISSUE TITLE
Automatic login from signup?

### ISSUE THREAD

**Issue by NetOperatorWibby** [florianheinemann/passwordless#102]
Is this possible to do? I'd like for people to get started ASAP and eliminating the email wait sounds like a great solution.

**Comment by adrianlee** [comment]
Looking at the code, it isn't possible at the moment.

A quick & dirty solution would to get requestToken to store the token in the request object so your /login route callback can access it and redirect to http://www.example.com?token=TOKEN&uid=UID.

**Comment by NetOperatorWibby** [comment]
Huh, that's a good hack! The redundant email is annoying though.

**Comment by NetOperatorWibby** [comment]
Since I created my own passwordless microservice, I can do this with ease.
