### ISSUE TITLE
use passwordless.requestToken in custom middleware 

### ISSUE THREAD

**Issue by yotavm** [florianheinemann/passwordless#103]
hey what i what do is to call  passwordless.requestToken insid anther middleware
its look like this 
```
const requestToken = (req, res, next) => {
  const passwordless = req.okliveOptions.passwordless;
  console.log(passwordless.requestToken);
  passwordless.requestToken((user, delivery, callback) => {

    callback(null, user);
  });
};
```
but is get stuck the function not working 
any help?

**Comment by florianheinemann** [comment]
I believe you're not calling `next()`

**Comment by yotavm** [comment]
where to call next ? 
passwordless.requestToken not call next ?

**Comment by florianheinemann** [comment]
The syntax is quite confusing there. Yes, requestToken calls next. However, your surrounding function doesn't seem to, or? And you don't seem to call requestToken in classic middleware fashion

**Comment by yotavm** [comment]
ok will try to fix this 
on more help from you look in #104 
i need help with accpetToken
sorry about the trouble
