### ISSUE TITLE
Magic link and code to be able to authenticate.

### ISSUE THREAD

**Issue by danielstaleiny** [florianheinemann/passwordless#105]
I have a question for this use case. 

I imagine that users can insert email address to login but they open email address in phone for example. Link will log them in phone. 

I want to know that if I want to create email with magic link and magic code/string to be able to type that into browser and log in there. 

Something similar to sms delivery strategy but for email. 

Do you support that ?
If not, How can I add this feature ? 

Also in documentation there is nothing mentioned with multiple social providers such as facebook. Should I use passport-facebook to achieve this.

**Comment by florianheinemann** [comment]
Hi,
Yes, it's supported. If you look at https://passwordless.net/docs/Passwordless.html#acceptToken you'll see that `acceptToken()` has a `allowPost` parameter

3rd party logins are not supported but you could probably combine passwordless with other APIs 

Cheers

**Comment by danielstaleiny** [comment]
Thanks a lot for pointing to right direction. I miss that one :) have nice one.
