### ISSUE TITLE
Login User on Signuphttps

### ISSUE THREAD

**Issue by laurisbernhart** [florianheinemann/passwordless#116]
Hi Florian,

What would be the best way to automatically login the user on signup? 
I was thinking it should be possible to chain middlewares like so:

- createUser
  // if successfully created call next()
- passwordless.requestToken(
  // find user
  // set request query params to include tokenField and uidField
  // next()
)
- passwordless.acceptToke(
  // res.send("account created and logged in")
)

Do you see any issues with this way?

Thank you in advance

**Comment by florianheinemann** [comment]
Well, there would be basically no way to prove that you're talking to the right person. Imagine, A already set up their account. Now, B using the address of A, also signs up and would get access to anything A had access to. Even if A isn't yet registered, B could manipulate the account in such a way that A might not be happy as soon as they sign up.

I believe you need a way to verify that you're talking to the right person

**Comment by laurisbernhart** [comment]
Of course you should not be able to login into an existing account through the signup page (which I would check on db level). I see no problem to automatically login a user when he just created an account.

that worked for me. Do you see any issues with this way?
![image](https://user-images.githubusercontent.com/10515029/38427977-97771b8c-39b2-11e8-9dfd-305c40d10fe8.png)

**Comment by florianheinemann** [comment]
No, I believe it should be ok if you think there is no issue with people manipulating the accounts of not-yet-registered users
