### ISSUE TITLE
send status if the email not existing

### ISSUE THREAD

**Issue by grega913** [florianheinemann/passwordless#118]
this is current function for sending a token to the email provided - - it works ok when the email is found in DB, however, if there's no email, the resonse send is 'Unautherised' - - > can someone please provide the solution for sending a custom made response when the user(email) is not found , that is the function that checks it (getUserRoleCredentials(user)) is rejected with an error:

  auth.post(
    "/sendtoken",
    passwordless.requestToken(
      (user, delivery, callback) => {
        admin
          .raw(getUserRoleCredentials(user))
          .then(res => normalizeCredentials(res))
          .then(() => {
            callback(null, user);
          })
          .catch(err => {
            if (process.env.NODE_ENV === "dev") {
              console.log(err);
            }
            callback(null, null);
          });
      },
      { failureRedirect: "/" }
    ),
    (req, res) => {
      const user = req.passwordless.uidToAuth;
      res.status(200).send({ uid: user });
    }
  );

**Comment by florianheinemann** [comment]
This might help: https://passwordless.net/deepdive#error-flashes
