### ISSUE TITLE
Manually setting req.user to entire user object from database

### ISSUE THREAD

**Issue by amlwwalker** [florianheinemann/passwordless#122]
I am using passwordless for when a user needs to reset a password. I.e send themselves an email, click on the link, get a temporary session (through passwordless), reset the password and carry on.

The short story, I am using graphql for my query language, and its strictness (and the design of my app) require req.user to have a series of fields (id etc etc). 

How can I configure passwordless to set req.user to a whole user object from a database, rather than just to the email address? Can I configure `passwordless.acceptToken()` in some way, or set some middleware?

FYI I am using passport.js to handle user authentication usually, passwordless is for the edge case of forgotten/compromised passwords.
I think it may have to do with the need to re-deserialise in passport or something?

Thanks

**Comment by florianheinemann** [comment]
Hi,

The second paragraph under the heading "10. - Who is logged in?" should help you: https://passwordless.net/getstarted

It's just about adding another tiny middleware
Cheers

**Comment by amlwwalker** [comment]
OK, thanks, I don't think passwordless is going to solve my problems if I can't customise how it sets req.user as I am using react, so it ends up being a lot of back and forth and I'm having to pass necessary fields as part of redirect query parameters as they are seperate apps.

Unless, as it alludes to here:
![image](https://user-images.githubusercontent.com/2920180/41344567-54d7de34-6ef9-11e8-8485-6d67effe4323.png)
That there is a way to change the default of setting `req.user` to the entire object not just the email, which would solve most of my problems.

Thanks!

**Comment by florianheinemann** [comment]
Yes, it alludes to that. It should exactely solve your issue
