### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by dolohow** [florianheinemann/passwordless#42]
Do you possible know why I am getting 400 all the time with the code in topic-passwordless branch here:
https://github.com/dolohow/icarus/tree/topic-passwordless

also are you using mailing list, irc or something?

**Comment by privateOmega** [comment]
I am encountering  a 400 bad request error. https://github.com/privateOmega/HIP/   I have used passwordless with loopback which is essentially express. Please ask me if more details are required.
