### ISSUE TITLE
authentication works, but how to do authorization? 

### ISSUE THREAD

**Issue by jzkunlun** [florianheinemann/passwordless#46]
Please add document to explain how to enable authorization. How does successful login pass the role to client?

**Comment by florianheinemann** [comment]
Hi! There is a line on it here: https://github.com/florianheinemann/passwordless#10-who-is-logged-in
Basically, the req.user object stores the information about *who* is logged in. All you have to do is interpret it on the server-side and pass whatever you need to the client-side. If you want to pass on additional information about the specific level of access, you might want to do an additional lookup from your database by adding another middleware layer.

If it's about not allowing access to certain pages see here: https://github.com/florianheinemann/passwordless#9-protect-your-pages

Does that help?

**Comment by jzkunlun** [comment]
Thank you for your support. I will poke around.

**Comment by florianheinemann** [comment]
Any progress? Otherwise, I would close this issue. Let me know, Florian

**Comment by jzkunlun** [comment]
Sure, you can close this issue.

Thanks,
