### ISSUE TITLE
passwordless + socket.io?

### ISSUE THREAD

**Issue by saphirre** [florianheinemann/passwordless#48]
hello florian, is it somehow possible to use passwordless together with socket.io? I mean to validate and use the token within socket.io instead of express?

**Comment by florianheinemann** [comment]
Hey! Can you be a bit more specific what you're trying to achieve? I'm not quite aware how socket.io actually works in the background but I almost fear that could be a bit of a stretch as Passwordless is quite tightly coupled to the idea of middleware...

**Comment by saphirre** [comment]
my idea was to authenticate a socket instead of an express session, thus validating the token during the socket.io handshake. when the client sends a valid token, the handshake succeeds, otherwise not.

since socket.io 1.0 uses middleware too, I already came up with the solution and adjusted the acceptToken() function accordingly.

I can show you a modified version of the example application if you're interested.

**Comment by florianheinemann** [comment]
Hey! That would indeed be interesting! Great to you were able to solve it!
Florian

**Comment by saphirre** [comment]
http://ge.tt/api/1/files/9e6Ha482/0/blob?download do not forget to run npm install first.
