### ISSUE TITLE
The example application seems no to work

### ISSUE THREAD

**Issue by Proxiweb** [florianheinemann/passwordless#49]
Hello,

Thanks for this lib. I'm trying to use it, but I can't get logged in.

So I tried to start from the example to gradually add features I want... but I can't get logged in the example too. I've just installed the example, bypassed the email to just log the url and return callback(). When I open the url, the page shows User: Not logged in... I can't figure what's happening...

**Comment by florianheinemann** [comment]
Hi!

Can you show me an example of the URL you're trying? And also maybe the replacement code you used for the bypass

Thank you!

Florian

**Comment by Proxiweb** [comment]
I've console logged the url generated :

http://localhost:3000/?token=3tmuWD5FJk5Mm5zMMfeg3Z&uid=dupont%40gmaill.com

**Comment by florianheinemann** [comment]
Hi! What makes me a bit suspicious is that UID contains your full email address rather than an ID. This can be ok, but usually you would want to translate it to an ID:

```
/* POST login details. */
router.post('/sendtoken', 
    passwordless.requestToken(
        // Turn the email address into an user ID
        function(user, delivery, callback) {
            // usually you would want something like:
            User.find({email: user}, callback(ret) {
               if(ret)
                  callback(null, ret.id)
               else
                  callback(null, null)
          })
          // but you could also do the following 
          // if you want to allow anyone:
          // callback(null, user);
        }),
    function(req, res) {
       // success!
          res.render('sent');
});
```
If you could maybe show me your code for requestToken / addDelivery that would really help

Florian

**Comment by hpaolini** [comment]
Sorry to jump in, but is node _really_ running locally? In other words, if the server has an address, the link should have been pointing directly to it, instead of `localhost`.

**Comment by Proxiweb** [comment]
@hpaolini, yes, express renders pages normally
@florianheinemann the email is form the example, but I'll try with a number.

**Comment by Proxiweb** [comment]
```javascript
var users = [
    { id: 1, email: 'marc@example.com' },
    { id: 2, email: 'alice@example.com' }
];


/* POST login screen. */
router.post('/sendtoken', 
	passwordless.requestToken(
		// Simply accept every user
		function(user, delivery, callback) {
			for (var i = users.length - 1; i >= 0; i--) {
			    if(users[i].email === user.toLowerCase()) {
				return callback(null, users[i].id);
			    }
			}
			callback(null, null);			
		}),
	function(req, res) {
  		res.render('sent');
});
```
It doesn't work, the url is http://localhost:3001/?token=9ZXR4918E3FHMPxo946yL2&uid=1

The page shows  User: Not logged in 

the mongodb passwordless-token collection is empty

**Comment by florianheinemann** [comment]
Just to be sure I downloaded the example and changed only(!) the addDelivery function to:

```javascript
passwordless.addDelivery(
    function(tokenToSend, uidToSend, recipient, callback) {
        // Send out token
			console.log(host + '?token=' + tokenToSend + '&uid=' + encodeURIComponent(uidToSend));
			callback();
        });
``
Everything else remained. When logging in it logs: `http://localhost:3000/?token=BX4abwVjGmE2hzJDF4NGfb&uid=test%40example.com' which logs me into the application.

The whole console log is:
```
node app.js
express-session deprecated undefined resave option; provide resave option app.js:55:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:55:9
Express server listening on port 3000
GET / 304 25ms
GET /stylesheets/style.css 304 3ms
GET /login 200 4ms - 575b
GET /stylesheets/style.css 304 3ms
http://localhost:3000/?token=BX4abwVjGmE2hzJDF4NGfb&uid=test%40example.com
POST /sendtoken 200 216ms - 388b
GET /stylesheets/style.css 304 2ms
GET /?token=BX4abwVjGmE2hzJDF4NGfb&uid=test%40example.com 302 135ms - 58b
GET / 200 5ms - 443b
GET /stylesheets/style.css 304 2ms
```

Is yours the same?

**Comment by Proxiweb** [comment]
idem :
```
express-session deprecated undefined resave option; provide resave option app.js:55:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:55:9
Express server listening on port 3000
GET / 200 141ms - 409b
GET /stylesheets/style.css 200 39ms - 110b
GET /login 200 32ms - 575b
GET /stylesheets/style.css 304 6ms
http://localhost:3000/?token=HGqdCihbbRL9AQSCesXMVX&uid=test%40example.com
POST /sendtoken 200 238ms - 388b
GET /stylesheets/style.css 304 2ms                                                                                                                                                              
GET /?token=HGqdCihbbRL9AQSCesXMVX&uid=test%40example.com 302 127ms - 58b                                                                                                                       
GET / 304 2ms                                                                                                                                                                                   
GET /stylesheets/style.css 304 1ms
```
When I open http://localhost:3000/?token=HGqdCihbbRL9AQSCesXMVX&uid=test%40example.com, I'm redirected to the homepage showing User: Not logged in. I have recloned the repository and only changed the lines you suggested... I'm on ubuntu, I've just done npm install, mongodb is running, the collection passwordless-token is empty... 

I'm going to try this on an other

**Comment by florianheinemann** [comment]
It's odd that Node returns a 304 for you when accessing the homepage after logging in. Maybe a caching issues here? You might want to try to paste the URL into a "private" tab to make sure that no cookies / caches are influencing the response.

Also: It's normal that there is nothing stored in MongoDB - but only after the token has been validated. So you might want to check if there is anything stored after requesting the token but _before_ logging in with it. If the database is still empty we would have limited the potential source of error to a very small section of the code...
