### ISSUE TITLE
Remotely log out user

### ISSUE THREAD

**Issue by stockholmux** [florianheinemann/passwordless#51]
I'm building a CMS around passwordless and I'm trying to figure out how to remotely logout a user. So, for example, an Admin user wants to kick a user from his/her session. 

What I'm doing right now doesn't seem to work:

```
thisRedisStore = new RedisStore(settings.redis.port, settings.redis.ip)
passwordless.init(thisRedisStore);

....

function logOutUser(req,res,next) {
  console.log('uid',req.params.uid);
  thisRedisStore.invalidateUser(req.params.uid,function(err){
    if (err) { next(err); } else {
      res.send({ status : 'ok'});
    }
  });
}
```

I have the admin user in one browser window and the user to kick in a private browser window. After I execute the `logOutUser` function (without error, because I'm seeing the `{status:"ok"}` response), the kicked user is still able to go around the site as if logged in. Am I missing something?

I can kick the user by deleting the redis key that corresponds to the session, but I'm not sure how the hash is determined to delete it and I'm not sure of the side effects of just deleting redis key.

**Comment by florianheinemann** [comment]
Hey,

You've solved part of the problem. `invalidateUser()` deletes the token from the database and hence makes it impossible to login with the same token. By default, this happens anyway after login.

The remaining problem is the same as with a classic username / password login: You need to delete the session of that particular user. One immediate idea that comes to me is that you (1) store the admin's request for logout somewhere and then (2) write a middleware that is triggered by every request and checks if the current user is on the list. If yes (3) invalidate the session and redirect the user to a page explaining what just happened.

Another approach might be this one:  https://stackoverflow.com/questions/19850413/is-it-possible-to-invalidate-or-delete-a-particular-users-session-data-in-expre 

Hope that helps!

**Comment by stockholmux** [comment]
Perfect! I didn't think of the middleware. I ended up doing something like this:

```
function forceLogout(req,res,next) {
  var
    forceMulti = client.multi();
  
  forceMulti
    .sismember(settings.keys.forceLogout,req.user)
    .srem(settings.keys.forceLogout,req.user);
  
  forceMulti.exec(function(err, results){
    var
      membership;
      
    if (err) { next(err); } else {
      membership = results[0];
      if (membership === 1) {
        
        res.redirect('/logout');
      } else {
        next();
      }
    }
  });
}
```

**Comment by babygirl2014** [comment]
On Feb 18, 2015 6:45 PM, "Florian Heinemann" <notifications@github.com>
wrote:
>
> Hey,
>
> You've solved part of the problem. invalidateUser() deletes the token
from the database and hence makes it impossible to login with the same
token. By default, this happens anyway after login.
>
> The remaining problem is the same as with a classic username / password
login: You need to delete the session of that particular user. One
immediate idea that comes to me is that you (1) store the admin's request
for logout somewhere and then (2) write a middleware that is triggered by
every request and checks if the current user is on the list. If yes (3)
invalidate the session and redirect the user to a page explaining what just
happened.
>
> Another approach might be this one:
https://stackoverflow.com/questions/19850413/is-it-possible-to-invalidate-or-delete-a-particular-users-session-data-in-expre
