### ISSUE TITLE
Can't use successRedirect with cookie-session

### ISSUE THREAD

**Issue by jpalardy** [florianheinemann/passwordless#53]
Here's a combination that doesn't work:

1. use the cookie-session
2. use successRedirect

In `_redirectWithSessionSave`, a callback is passed to `req.session.save(...)` ... but the cookie-session `save()` function doesn't take a callback: the redirect (in the callback) won't be called. The req just hangs.

Here's the code:

![redirect](https://cloud.githubusercontent.com/assets/18142/7291014/32c4f3de-e93e-11e4-9ca2-c9e3354b37e8.png)

I'm not sure what the right solution is ... maybe checking the `req.session.save` arity and calling it either in sync/async mode, as the case might be.

**Comment by florianheinemann** [comment]
Sorry for the long wait! It's solved with 1.1.0 - While not a perfect solution I introduced an optional flag `passwordless.init(tokenStore, {skipForceSessionSave: true})` Maybe something better will come along :)
