### ISSUE TITLE
Using passwordless with Express & Mongoose

### ISSUE THREAD

**Issue by Jessestr** [florianheinemann/passwordless#54]
So I'm using Express & Mongoose for my application and I wanted to do the authentication myself but Passwordless seems the way to go. I love tokens:)!

But is it possible to just store the tokens in my already existing database?

Thanks

**Comment by florianheinemann** [comment]
Hi! Yes, absolutely. Just connect to the existing MongoDB database using passwordless-mongostore. As long as you choose a collection that isn't in use yet it will just amend the database.

**Comment by Jessestr** [comment]
Florian, thanks for your response. Having a hard time installing bcrypt on Windows though. I wonder why this "passwordless" thing isn't used much more. Looks so convenient.

**Comment by florianheinemann** [comment]
Thanks! You can use
https://www.npmjs.com/package/passwordless-mongostore-bcrypt-node which is
closer but doesn't need bcrypt

Florian
