### ISSUE TITLE
Is this suitable also for rest server API

### ISSUE THREAD

**Issue by benag** [florianheinemann/passwordless#59]
Does this work also for rest API points: PUT,POST,DELETE ..

**Comment by florianheinemann** [comment]
Hey, I think it should, but I haven't tried it yet. You probably would want
to use it in stateless mode:
https://passwordless.net/deepdive#stateless-operation

Let me know if it works!

**Comment by benag** [comment]
Do i need to add the token and uid to each request utl?

**Comment by florianheinemann** [comment]
You can certainly use sessions as you would normally. However, depending on
your use case you might have very infrequent API requests where a stateless
operation might be beneficial
