### ISSUE TITLE
Different Email bodies depending on input

### ISSUE THREAD

**Issue by amlwwalker** [florianheinemann/passwordless#60]
Hi,
I am creating dynamic email bodies and want to be able to specify which body to use ( from a range of templates) when the token is sent to the recipient. 
For instance if `delivery === 'template1'` then it will send one body, etc etc for template2/3...
These templates have different fields that need filling before sending, but I won't know what the values are until just before sending.

```
passwordless.addDelivery('templateX', function(tokenToSend, uidToSend, recipient,
        callback) {
```

addDelivery doesn't seem to allow me to pass in other paramers - for instance the name of the template to use, and the parameters to populate it with.

Can you recommend a way for me doing this please?

EDIT:
I suppose the bit I want to be able to pass in are the parameters to the message object that will then be used by mandrill to send the email

```
        var message = {
            "html": emailText(true, tokenToSend, uidToSend),
            "text": emailText(false, tokenToSend, uidToSend),
            "subject": config.mandrill.subject,
            "from_email": config.mandrill.from,
            "from_name": config.mandrill.fromname,
            "to": [{
                "email": recipient,
                "name": "",
                "type": "to"
            }],
            "headers": {
                "Reply-To": config.mandrill.from
            },
        };
```
Thanks
Alex

**Comment by olivierlizotte** [comment]
Any progress on this issue?

**Comment by florianheinemann** [comment]
Hey,

Sorry for the delay on that one. To be sure: Wouldn't adding several delivery strategies not answer the problem? https://passwordless.net/deepdive#several-delivery-strategies 

I agree it's not a perfect solution but might be a first workaround. As a next step it would indeed make sense to pass the req object

Cheers

**Comment by olivierlizotte** [comment]
Hey,
In my case, I render an email template through Jade using the req object. Also, passing values would allow me to have the user info (instead of querying the database based on the email address).

Thanks!

**Comment by florianheinemann** [comment]
Hope this helps! Thanks for the input!

**Comment by olivierlizotte** [comment]
Thank you! It really helps! :)
