### ISSUE TITLE
Is it possible to bypass the signup 

### ISSUE THREAD

**Issue by erwin16** [florianheinemann/passwordless#62]
Is it possible to send directly tokens to users registered by an admin...  some internal users will never signup ... only login/logout ...

**Comment by florianheinemann** [comment]
Hey,

I'm not quite sure what you want to achieve. Do you want to:
1. Centrally send links to your users without them ever taking any action? E.g. through a newsletter, etc.
2. Allow certain users to have a no registration but to only have to type in their email whenever they want to login?
3. Have for certain users always the same login link

All three are possible but let me know which one you try to do! :-)

Florian

**Comment by alice0meta** [comment]
I want to be able to do # 2.

**Comment by florianheinemann** [comment]
Hey,

You could either accept every single user as shown here:
https://github.com/florianheinemann/passwordless/blob/master/examples/simple-mail/routes/index.js#L33

Or you could at the same place have the normal approach (as shown in the example in the commented out section) but check beforehand if the user belongs to a certain group and then just use the code as for the first example.

Hope that helps

Florian
