### ISSUE TITLE
Use with angular single page router

### ISSUE THREAD

**Issue by kr4ft3r** [florianheinemann/passwordless#64]
Is there some trick to make this module work with angular router on a single page app? What I mean is, when using nodeJS for API and angular for front-end app, direct URL and API calls are secured, but clicking on menu links in angular app will just open the restricted page.

All I can think of is have angular router do a redirection if user data is not present, but maybe someone knows most elegant and secure way to do this.

**Comment by florianheinemann** [comment]
Not sure I completely understand the situation (and I'm not 100% into Angular). However: If some parts of your single-page app shouldn't be seen by the client, then it should not have been loaded at all, or? All restricted content should be loaded on-demand (even in a single page app). Those URLs that are used to load the additional content can easily be restricted. If they return with a 401 your app knows that the content is restricted and can e.g. display a login field. All of that could be done on one single page
