### ISSUE TITLE
Prevent spamming emails of registered users?

### ISSUE THREAD

**Issue by serganus** [florianheinemann/passwordless#65]
Hi,

Great library but I have a stupid question. Is there a way to prevent spamming the email of registered user by the random attacker?

Any suggestions for writing error handling would be appreciated!

I use express 4.X.

**Comment by NoNameProvided** [comment]
Hi seganus! 

I think the easiest way is to store the IP address of the requests. And start to delay or entirely prevent sending new emails after the third or x try.

**Comment by florianheinemann** [comment]
Hi
Let me recommend a slight amendment to @NoNameProvided 's proposal: Rather than blocking the IP address I would likely store the time of last request for each email address and delay/block on that basis. IP blocking could be another step but is a difficult topic as proxys / TOR / VPN are all resulting in shared IP addresses of several users... Blocking limits would hence have to be much higher if based on IPs.
Cheers

**Comment by serganus** [comment]
Thanks for the suggestions. I think express-brute might fit well. I have another question, is there a way to pass token in ejs as <%= token %> after successful accepting the token?

**Comment by florianheinemann** [comment]
Can you detail what exactly you try to do? :) 
Cheers

**Comment by serganus** [comment]
(1) I have a POST request handled by AJAX Jquery that should work when the value of "x-access-token" is set up by the server side call. Actually, I use every token generated to assign roles to specific users.

(2) I have an API route that passes data to some device (IOT). Since its used outside the main app, I have to set a token for it to work.

If it was a session based authentication I would generate a CSRF and pass that always for POST request. Since here I already have a token just need to pass it to work.

Thanks again for the valuable comments/suggestions.

**Comment by florianheinemann** [comment]
For step 2: That request originates directly from the client? Why do you need a token? Can't you just push the data to the device?

**Comment by serganus** [comment]
Lets assume that the remote client is not a browser and only understands JSON.

(1) Before Token based authentication 
`app.get('/data/:id, require('somecode).GETJSON);`
`On GET /data/35246523654623545` - I great raw JSON stream 

(2) After Token based authentication 

`var restricted = passwordless.restricted({ failureRedirect: '/login' });`
`app.get('/data/:id, restricted, require('somecode).GETJSON);`
`On GET /data/35246523654623545` - I great html content for /login

(3) Solution i think

`var restricted = passwordless.restricted({ failureRedirect: '/login' });`
`app.get('/data/:id, restricted, require('somecode).GETJSON);`
`On GET /data/35246523654623545?token=VALUE&uid=VALUE` I great raw JSON stream
`
(4) Offcourse i can implement this directly in ejs

`<a href="/data/<%= id %>?token=<%= token %>&uid=<%= uid %>">Dummy data stream </a>
`
I figured <%= uid %> but not sure how to get <%= token %>?
