### ISSUE TITLE
"static" tokens

### ISSUE THREAD

**Issue by matteocontrini** [florianheinemann/passwordless#66]
Hi,
on my website I plan to use email tokens for authentication.
But I've would like to also send out notifications via email (something like a newsletter that is differently generated for every user). I'd like to put in these emails that go out a button that says "enter the website" and that button should open the website and log the user in.

Is it something that can be done in some way with passwordless or is it an unsupported scenario?

Thanks.

**Comment by florianheinemann** [comment]
Hey,
While I did not have this use case in mind when developing passwordless you could certainly make it happen. What you would have to do is:
1.) Manually generate a token: `passwordless._generateToken()` is the way to go (alternatively: `passwordless._generateNumberToken(max)`). See the comments in the library to learn more about the functions
2.) Manually add the token to your TokenStore. For example, when you use MongoStore you can call: `mongostore.storeOrUpdate(token, UID, msForTokenToBeValid, null, function(err) {})` The comments in the lib should help you again: https://github.com/florianheinemann/passwordless-tokenstore/blob/master/lib/tokenstore.js#L35
3.) Send the email using the token from step (1) and embedding it in the appropriate URL

The rest of passwordless should be implemented as usual (incl. adding the necessary routes to accept incoming tokens, etc.)

Let me know if it works!
Cheers

**Comment by matteocontrini** [comment]
Thanks for the fast reply and the strategy! I'll see what to do :)
