### ISSUE TITLE
Callback for passwordless.acceptToken()

### ISSUE THREAD

**Issue by serganus** [florianheinemann/passwordless#67]
Hi,

I have been implementing [express-brute](https://www.npmjs.com/package/express-brute) for my app that uses passwordless.

I need to add a callback to accepttoken that would just reset the counts for that specific user. I don't know how to add?

Present code :
`app.use(passwordless.acceptToken({
successRedirect: '/',
successFlash: 'You have successfully loggedin! ',
failureFlash: 'Oops! something went wrong. Please try login again!.' 
}));`

Code that i want to add to acceptToken() as callback :

`var callback = function(req, res) {
req.brute.reset(function () {
        res.redirect('/UI'); // logged in, send them to the home page
    });
}`

I failed when i did this :

`app.use(passwordless.acceptToken({
successRedirect: '/',
successFlash: 'You have successfully loggedin! ',
failureFlash: 'Oops! something went wrong. Please try login again!.' 
},callback));`

**Comment by pedrovagner** [comment]
Why did this issue close? I need a callback that receive the `origin` url.
