### ISSUE TITLE
HMAC

### ISSUE THREAD

**Issue by anaibol** [florianheinemann/passwordless#71]
Hi, thanks for this sharing this idea and this package!
I was thinking to not store the tokens, but validate them using HMAC, like I use for validating the user accessToken present in the cookie.
What do you think about? Is it possible to detach the "store" part of this module?

Thanks!

**Comment by florianheinemann** [comment]
Hey!

Not quite sure what you try to do, but you can always write your own storage module: https://github.com/florianheinemann/passwordless-tokenstore-test 

E.g., you could write a thin layer above one of the standard storage modules (e.g. MongoDB) and just make sure all the tests from the link above pass

Cheers
