### ISSUE TITLE
acceptToken false positive

### ISSUE THREAD

**Issue by aabenoja** [florianheinemann/passwordless#72]
I have a 2FA email scheme, and I'm currently running into a false positive. `_tokenStore.authenticate` is invoking the callback with `valid` set to false but `error` as null. If I were using the flash messaging, I could catch it, but since I am not I'm going through my middleware stack with an "invalid user" and no errors. I'm not sure if this is by design for 2FA.

**Comment by florianheinemann** [comment]
Hey,

Could you detail a bit further what your intended middleware flow is? You could always check for req["user"] to be set.

Cheers

**Comment by aabenoja** [comment]
I found my issue. I had my `uid` and `token` values reversed, so my redis tokenstore lookup would fail on that lookup, which leads to that scenario described above. The error was completely on my setup, but it was difficult to track down the actual issue, mostly because it looked like the `acceptToken` middleware was succeeding when the authentication step truly failed.

For documentation's sake should the deep dive recommend we check that has been set on the request before generating the post response?
