### ISSUE TITLE
Help with Cookie-Session Support

### ISSUE THREAD

**Issue by andreafalzetti** [florianheinemann/passwordless#75]
I need the sessions to be persistent when the application restarts, I've found [this](http://stackoverflow.com/questions/23260676/express-4-sessions-not-persisting-when-restarting-server) so I've migrated my project from the standard express-session to [cookie-session](https://github.com/expressjs/cookie-session) and the integration with passwordless works fine.

There's only one problem that I've temporary patched (but I need to find a proper way to put it in production) which is:

After logging out, the session is destroyed and when I call any route that is restricted by the passwordless middleware, the next() is never called so the browser gets stuck. 

### Code

I have the following route

**Express App**
```
app.set('trust proxy', 1);
app.use(cookieParser());
app.use(cookieSession({
	name: 'projectName.sess',
	keys: ['key1', 'key2'],
	secret: 'secret here',
	maxAge: 1000*60*60*24*30
}));
app.use(passwordless.sessionSupport());
```

**Logout**
```
router.get('/logout', passwordless.logout(),
	function(req, res) {
  res.redirect('/');
});
```

**Profile**

```
router.get('/profile', passwordless.restricted({ failureRedirect: '/signin', failureFlash: 'Please login to view your profile.' }),
    function(req, res) {
        res.render('profile', { user: req.user });
});
```

**The problem in /lib/passwordless/passwordless.js:605-611**

```
		req.session.save(function(err) {
			if (err) {
				return next(err);
			} else {
				res.redirect(target);
			}
		});
```

Apparently using cookie-session the *save* function's callback (err) is not invoked and the if statement is never executed.

I've temporary fixed replacing this entire block with the following:
```
req.session.save();
res.redirect(target);
```

but I'm not 100% sure that I'm doing it right.

I hope you can help me on this :)

**Comment by florianheinemann** [comment]
Hey,

Thanks for reaching out. This is a known issue with cookie-session. You can simply set `skipForceSessionSave: true` as option in `init()`

See: https://passwordless.net/docs/Passwordless.html#init 

`save()` doesn't have to be called explicitly in that case

Hope it helps!

**Comment by andreafalzetti** [comment]
Thanks for the quick support. It works great! :)
