### ISSUE TITLE
question: sending token via header

### ISSUE THREAD

**Issue by vvavepacket** [florianheinemann/passwordless#76]
Is it possible to send token via headers? (instead of appending token and uid at the url)? Thanks in advance.

**Comment by florianheinemann** [comment]
Hi!

Very interesting question. There is no out of the box support but I see two options:
(1) write a one-line middleware that queries the header and overwrites req.query["uid"]
(2) write a PR that adds this functionality as an option to the library including the relevant tests 

Cheers
