### ISSUE TITLE
multiple tokens/logins - keep old tokens working

### ISSUE THREAD

**Issue by amlwwalker** [florianheinemann/passwordless#79]
Hi,

Quick one,

If I enter an email address, and it sends me a token, then I enter the same email address and it sends me another token, only the most recent token works. Is there a way to make old tokens that haven't been used work without invalidating them, I'm sure there must be a flag I can set somewhere but I can't find it.

Thanks

**Comment by florianheinemann** [comment]
Hi,

Indeed, only the most recent token works and there is no option to change this behavior. This would have to be implemented on the level of the TokenStore. If you require the behavior you could fork one of the existing TokenStores for the database of your choice

Cheers
