### ISSUE TITLE
Is there a way to persist tokens even when the server is restarted?

### ISSUE THREAD

**Issue by NetOperatorWibby** [florianheinemann/passwordless#88]
If there is, I'd love to learn how to achieve this!

**Comment by florianheinemann** [comment]
Yes, there is! Simply use one of the TokenStores that store the tokens persistently in a database (Postgres, Mongo, Redis, ...): https://passwordless.net/plugins

**Comment by NetOperatorWibby** [comment]
Sweet, thanks! It appears that I was on the way to implementing this but never finished.

**Comment by NetOperatorWibby** [comment]
@florianheinemann It's not working for me. Here is my `auth/index.js` file:

```
module.exports = (app) => {

  passwordless.init(new MongoStore(mongoURI, {
    server: {
      auto_reconnect: true
    },
    mongostore: {
      collection: "fuckPasswords"
    }
  }));

  passwordless.addDelivery((tokenToSend, uidToSend, recipient, callback) => { ... });

  app.use(passwordless.sessionSupport());
  app.use(passwordless.acceptToken());

};
```

I'm able to login fine and *before I login*, I can see an entry in my collection but it disappears when I login.

**Comment by florianheinemann** [comment]
That's intentional. Tokens are one-time only for security reasons. You can change this here: https://passwordless.net/deepdive#allow-token-reuse

**Comment by NetOperatorWibby** [comment]
Ah damn, okay. Is it possible to allow limited reuse? Like, only 3 uses? I figure that's something I'd have to code myself.

**Comment by NetOperatorWibby** [comment]
For some reason, token reuse isn't working for me.

```
passwordless.init(new MongoStore(mongoURI, {
  server: {
    auto_reconnect: true
  },
  mongostore: {
    collection: "fuckPasswords"
  }
}), { allowTokenReuse: true });
```

Will update if/when I discover a solution.

**Comment by NetOperatorWibby** [comment]
The [example and module here](https://www.npmjs.com/package/connect-mongodb-session) helped, 5 months later.

Yes!
