### ISSUE TITLE
User needs to login again after server restart

### ISSUE THREAD

**Issue by arkadutta87** [florianheinemann/passwordless#90]
I have tried with your example at https://github.com/florianheinemann/passwordless/tree/master/examples/simple-mail.
 
In this example also after server restart user needs to login again for having access to the restricted url.

 --- Normal login happening properly, if the server is not restarted the user need not login back again but once server restarts he needs to login again ---

Kindly help --- 

**--------My actual applicaiton code is below --** 

import express from 'express';
import expressHandleBars from 'express-handlebars';
import path from 'path';
import cookieParser from 'cookie-parser';
import compression from 'compression';
import bodyParser from 'body-parser';
import ms from 'ms';
import ExpressWinston from 'express-winston';
import expressSession from 'express-session';
import passwordless from 'passwordless';
import MongoStore from 'passwordless-mongostore';
import emailJs from 'emailjs';
//import mongo from 'mongodb';
import monk from 'monk';
import ses from 'node-ses';
import apiRequestHandler from './ApiRequestHandler';

const sesKey = 'XXXXXXXXXXXXXX';
    const sesSecret = 'xxxxxxxxxxxxxxx';
    const awsInstance = 'https://xxxxxxxxxxxx.com';
    const sesClient = ses.createClient({ key: sesKey, secret: sesSecret, amazon: awsInstance});

    const sesFromMailID = 'xxxxxxxx';

    const mongoHost = 'localhost';
    const mongoPort = '27017';
    const databaseMongo = 'passwordless-simple-mail';
    const userDataBase = 'humane-cockpit-yyyyyyyyyyy';

    // TODO: MongoDB setup (given default can be used)
    const pathToMongoDb = `mongodb://${mongoHost}:${mongoPort}/${databaseMongo}`;

    const db = monk(`${mongoHost}:${mongoPort}/${userDataBase}`);

    // TODO: Path to be send via email -- to be configurable
    const host = 'http://localhost/';

    // Setup of Passwordless
    passwordless.init(new MongoStore(pathToMongoDb, {
        server: {
            auto_reconnect: true
        },
        mongostore: {
            collection: 'token'
        }
    }), { allowTokenReuse: true });

    passwordless.addDelivery(
        (tokenToSend, uidToSend, recipient, callback) => {
            console.log(`$$$$$$$$$$$--------- Token Send : ${tokenToSend} , uidToSend : ${uidToSend} , recipient : ${recipient}`);
            // Send out token
            sesClient.sendEmail({
                to: recipient,
                from: sesFromMailID,
                subject: 'Login link for Humane-Cockpit Dashboard',
                message: `Hello!
                You can now access your account here: ${host}?token=${tokenToSend}&uid=${encodeURIComponent(uidToSend)}`
            }, (err, data, res) => {
                if (err) {
                    console.log(err);
                }
                callback(err);
            });
        });

   
    app.use(compression());

    if (config.client) {
        // view engine setup
        const viewsDirectory = config.client.views || path.join(__dirname, 'views');
        const layoutsDirectory = path.join(viewsDirectory, 'layouts');

        const hbsEngine = expressHandleBars.create({
            layoutsDir: layoutsDirectory,
            defaultLayout: 'default'
        });

        app.set('views', viewsDirectory);
        app.engine('handlebars', hbsEngine.engine);
        app.set('view engine', 'handlebars');

        if (config.client.publicPath) {
            app.use(config.client.multiInstance ? '/:instanceName' : '/', express.static(config.client.publicPath, {
                index: false,
                maxAge: XXXXXXXX
            }));
        }

        if (config.client.resourcesPath) {
            app.use(config.client.multiInstance ? '/:instanceName/resources' : '/resources', express.static(config.client.resourcesPath, {
                index: false,
                maxAge: XXXXXXXX
            }));
        }
    }

    // For API and dynamic resources
    app.use((req, res, next) => {
        res.header('Access-Control-Allow-Origin', '*');
        res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
        res.header('Cache-Control', 'private, no-cache, no-store, must-revalidate');
        res.header('Expires', '-1');
        res.header('Pragma', 'no-cache');
        next();
    });

    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({extended: false}));
    app.use(cookieParser());
    app.use(expressSession({secret: 'xxxxxxxxxxxx', saveUninitialized: true, resave: true, cookie: { maxAge: 365 * 24 * 60 * 60 * 1000 }}));

    // TODO; >>>>>> enabled only when passwordless
    //passwordless code
    app.use(passwordless.sessionSupport());
    app.use(passwordless.acceptToken({successRedirect: '/'}));

    app.get('/login', (req, res) => {
        if (req.user) {
            res.redirect('/');
        } else if (req.loginFailed) {
            res.render('login', {loginFailed: true});
        } else {
            res.render('login', {user: req.user});
        }
    });

    app.post('/sendtoken',
        passwordless.requestToken(
            // Simply accept every user
            (user, delivery, callback, req) => {
                console.log(`User Object : ${JSON.stringify(user)}`);
                console.log(`request object : ${JSON.stringify(req.body)}`);

                //const dbInst = req.db;
                const userName = req.body.user;
                const instanceName = req.body.instanceName;

                // Fetch from 'users' collection
                const loginCollection = db.get('login');
                loginCollection.findOne({username: userName, instanceName, isEnabled: true}, (e, doc) => {
                    if (e) {
                        console.log(e);
                        req.loginStatus = false;
                        callback(null, null);
                    } else if (doc) {
                        console.log(JSON.stringify(doc));
                        //req.name = doc.name;
                        callback(null, doc._id);
                    } else {
                        req.loginFailed = true;
                        callback(null, null);
                    }
                });
                // usually you would want something like:
            }, {failureRedirect: '/login'}),
        (req, res) => {
            res.render('login', {tokenSent: true});
        });

    app.use((req, res, next) => {
        console.log('\n\n$$$$$$ ---- Inside The Code for Arka ----- $$$$$$$$ \n\n');
        if (req.user) {
            console.log('$$$$$ ---- Inside the code to set __userContext__ ');

            //const dbInst = req.db;
            const loginCollection = db.get('login');
            loginCollection.findById(req.user, (error, user) => {
                console.log(`User returned from ID --- : ${JSON.stringify(user)}`);
                req.__userContext__ = user;
                next();
            });
        } else {
            next();
        }
    });

    app.all('/*', passwordless.restricted({failureRedirect: '/login'}), (req, res, next) => {
        next();
    });

    app.get('/logout', passwordless.logout(),
        (req, res) => {
            res.redirect('/login');
        });

    if (config.api) {
        app.use(apiRequestHandler(config.api));
    }

    //
    // CLIENT APP
    //
    if (config.client) {
        // eslint-disable-next-line import/no-unresolved, import/no-extraneous-dependencies
        const clientAppRequestHandler = require('reactjs-web-boilerplate/lib/server/ClientAppRequestHandler').default;

        app.use(config.client.multiInstance ? '/:instanceName' : '/', clientAppRequestHandler(config.client.routes, config.client.multiInstance, config.client.properties, config.api));
    }

    // TODO: depending on the user agent either return REST response or page response here
    // catch 404 and forward to error handler
    app.use((req, res, next) => {
        const err = new Error('404::Not Found');
        err.status = 404;
        next(err);
    });

    app.use(ExpressWinston.errorLogger({winstonInstance: logger}));

    //
    // ERROR HANDLERS
    //

    // TODO: depending on the user agent either return REST response or page response here
    // development error handler - will print stacktrace
    if (app.get('env') === 'development') {
        app.use((err, req, res) => {
            res.status(err.status || 500);
            // res.render('error', {
            //     message: err.message,
            //     error: err
            // });
            res.send({message: err.message, status: err.status, error: err});
        });
    }

    // TODO: depending on the user agent either return REST response or page response here
    // production error handler- no stack traces leaked to user
    app.use((err, req, res) => {
        res.status(err.status || 500);
        // res.render('error', {
        //     message: err.message,
        //     error: {}
        // });
        res.send({message: err.message, status: err.status});
    });

**Comment by florianheinemann** [comment]
Hi,

This is most likely not caused by passwordless but by the way the sessions are stored. By default, express-session uses MemoryStore which will not persist after a restart. 

Please see https://github.com/expressjs/session and in particular https://github.com/expressjs/session#compatible-session-stores

Cheers

**Comment by arkadutta87** [comment]
passwordless-mongostore - what does this do ... can you point me to a persistent session with passwordless example ... I am dead stuck ..

**Comment by florianheinemann** [comment]
Passwordless-Mongostore stores the tokens. In addition, you have the typical session management that is the counterpart to the cookies the users store on their computers. If you restart the server the user keeps his cookie, but the server doesn't know anything about the session/cookie anymore. That's why you need to store those as well.

My website www.passwordless.net uses express-session but with persistent storage. Here is the source code: https://github.com/florianheinemann/www-passwordless-net/blob/master/app.js

**Comment by arkadutta87** [comment]
****Thanks sir --** 

The fully working code for future reference ---** 

import express from 'express';
import expressHandleBars from 'express-handlebars';
import path from 'path';
import cookieParser from 'cookie-parser';
import compression from 'compression';
import bodyParser from 'body-parser';
import ms from 'ms';
import ExpressWinston from 'express-winston';
import sessionStore from 'connect-mongo';
import expressSession from 'express-session';
import passwordless from 'passwordless';
import MongoStore from 'passwordless-mongostore';
import emailJs from 'emailjs';
//import mongo from 'mongodb';
import monk from 'monk';
import ses from 'node-ses';
import apiRequestHandler from './ApiRequestHandler';

const sesKey = 'XXXXXXXXXXXXXX';
const sesSecret = 'xxxxxxxxxxxxxxx';
const awsInstance = 'https://xxxxxxxxxxxx.com';
const sesClient = ses.createClient({ key: sesKey, secret: sesSecret, amazon: awsInstance});

const sesFromMailID = 'xxxxxxxx';

const mongoHost = 'localhost';
const mongoPort = '27017';
const databaseMongo = 'passwordless-simple-mail';
const userDataBase = 'humane-cockpit-yyyyyyyyyyy';

// TODO: MongoDB setup (given default can be used)
const pathToMongoDb = `mongodb://${mongoHost}:${mongoPort}/${databaseMongo}`;

const db = monk(`${mongoHost}:${mongoPort}/${userDataBase}`);

//TODO: express-session mongo store
    const MongoStoreSession = sessionStore(expressSession);

// TODO: Path to be send via email -- to be configurable
const host = 'http://localhost/';

// Setup of Passwordless
passwordless.init(new MongoStore(pathToMongoDb, {
    server: {
        auto_reconnect: true
    },
    mongostore: {
        collection: 'token'
    }
}));

passwordless.addDelivery(
    (tokenToSend, uidToSend, recipient, callback) => {
        console.log(`$$$$$$$$$$$--------- Token Send : ${tokenToSend} , uidToSend : ${uidToSend} , recipient : ${recipient}`);
        // Send out token
        sesClient.sendEmail({
            to: recipient,
            from: sesFromMailID,
            subject: 'Login link for Humane-Cockpit Dashboard',
            message: `Hello!
            You can now access your account here: ${host}?token=${tokenToSend}&uid=${encodeURIComponent(uidToSend)}`
        }, (err, data, res) => {
            if (err) {
                console.log(err);
            }
            callback(err);
        });
    });



app.use(compression());

if (config.client) {
    // view engine setup
    const viewsDirectory = config.client.views || path.join(__dirname, 'views');
    const layoutsDirectory = path.join(viewsDirectory, 'layouts');

    const hbsEngine = expressHandleBars.create({
        layoutsDir: layoutsDirectory,
        defaultLayout: 'default'
    });

    app.set('views', viewsDirectory);
    app.engine('handlebars', hbsEngine.engine);
    app.set('view engine', 'handlebars');

    if (config.client.publicPath) {
        app.use(config.client.multiInstance ? '/:instanceName' : '/', express.static(config.client.publicPath, {
            index: false,
            maxAge: XXXXXXXX
        }));
    }

    if (config.client.resourcesPath) {
        app.use(config.client.multiInstance ? '/:instanceName/resources' : '/resources', express.static(config.client.resourcesPath, {
            index: false,
            maxAge: XXXXXXXX
        }));
    }
}

// For API and dynamic resources
app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
    res.header('Cache-Control', 'private, no-cache, no-store, must-revalidate');
    res.header('Expires', '-1');
    res.header('Pragma', 'no-cache');
    next();
});

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: false}));
app.use(cookieParser());
app.use(expressSession(
        {
            secret: 'xxxxx',
            saveUninitialized: false,
            resave: false,
            cookie: {maxAge: 365 * 24 * 60 * 60 * 1000},
            store: new MongoStoreSession({
                db: databaseMongo,
                host: 'localhost',
                port: 27017,
                collection: 'session',
                auto_reconnect: true,
                url: `mongodb://localhost:27017/${databaseMongo}`
            })
        }
    ));

//passwordless code
app.use(passwordless.sessionSupport());
app.use(passwordless.acceptToken({successRedirect: '/'}));

app.get('/login', (req, res) => {
    if (req.user) {
        res.redirect('/');
    } else if (req.loginFailed) {
        res.render('login', {loginFailed: true});
    } else {
        res.render('login', {user: req.user});
    }
});

app.post('/sendtoken',
    passwordless.requestToken(
        // Simply accept every user
        (user, delivery, callback, req) => {
            console.log(`User Object : ${JSON.stringify(user)}`);
            console.log(`request object : ${JSON.stringify(req.body)}`);

            //const dbInst = req.db;
            const userName = req.body.user;
            const instanceName = req.body.instanceName;

            // Fetch from 'users' collection
            const loginCollection = db.get('login');
            loginCollection.findOne({username: userName, instanceName, isEnabled: true}, (e, doc) => {
                if (e) {
                    console.log(e);
                    req.loginStatus = false;
                    callback(null, null);
                } else if (doc) {
                    console.log(JSON.stringify(doc));
                    //req.name = doc.name;
                    callback(null, doc._id);
                } else {
                    req.loginFailed = true;
                    callback(null, null);
                }
            });
            // usually you would want something like:
        }, {failureRedirect: '/login'}),
    (req, res) => {
        res.render('login', {tokenSent: true});
    });

app.use((req, res, next) => {
    console.log('\n\n$$$$$$ ---- Inside The Code for Arka ----- $$$$$$$$ \n\n');
    if (req.user) {
        console.log('$$$$$ ---- Inside the code to set __userContext__ ');

        //const dbInst = req.db;
        const loginCollection = db.get('login');
        loginCollection.findById(req.user, (error, user) => {
            console.log(`User returned from ID --- : ${JSON.stringify(user)}`);
            req.__userContext__ = user;
            next();
        });
    } else {
        next();
    }
});

app.all('/*', passwordless.restricted({failureRedirect: '/login'}), (req, res, next) => {
    next();
});

app.get('/logout', passwordless.logout(),
    (req, res) => {
        res.redirect('/login');
    });

if (config.api) {
    app.use(apiRequestHandler(config.api));
}

//
// CLIENT APP
//
if (config.client) {
    // eslint-disable-next-line import/no-unresolved, import/no-extraneous-dependencies
    const clientAppRequestHandler = require('reactjs-web-boilerplate/lib/server/ClientAppRequestHandler').default;

    app.use(config.client.multiInstance ? '/:instanceName' : '/', clientAppRequestHandler(config.client.routes, config.client.multiInstance, config.client.properties, config.api));
}

// TODO: depending on the user agent either return REST response or page response here
// catch 404 and forward to error handler
app.use((req, res, next) => {
    const err = new Error('404::Not Found');
    err.status = 404;
    next(err);
});

app.use(ExpressWinston.errorLogger({winstonInstance: logger}));

//
// ERROR HANDLERS
//

// TODO: depending on the user agent either return REST response or page response here
// development error handler - will print stacktrace
if (app.get('env') === 'development') {
    app.use((err, req, res) => {
        res.status(err.status || 500);
        // res.render('error', {
        //     message: err.message,
        //     error: err
        // });
        res.send({message: err.message, status: err.status, error: err});
    });
}

// TODO: depending on the user agent either return REST response or page response here
// production error handler- no stack traces leaked to user
app.use((err, req, res) => {
    res.status(err.status || 500);
    // res.render('error', {
    //     message: err.message,
    //     error: {}
    // });
    res.send({message: err.message, status: err.status});
});
