### ISSUE TITLE
secure: true for session cookie not supported?

### ISSUE THREAD

**Issue by simevidas** [florianheinemann/passwordless#93]
I’ve noticed that when I use this session configuration

    app.use(session({ 
        secret: process.env.SESSION_SECRET,
        store: new MongoStore({ url: process.env.MONGODB_URL }),
        cookie: { secure: true, maxAge: 3628800000 }, // 6 weeks
        resave: false,
        saveUninitialized: false
    }));

passwordless does not work, specifically `req.session.passwordless` and `req.user` are undefined. However, if I remove the `secure: true` option, it works.

My site is HTTPS as much as possible, from what I understand. I use CloudFlare Full (Strict) SSL and HSTS, and all the URLs that I used for testing were `https:`. I’m not sure what’s going on here. I will leave out the `secure: true` part for now, but if anyone makes it work with it, please let me know.

**Comment by florianheinemann** [comment]
Can you try my answer to #75? https://github.com/florianheinemann/passwordless/issues/75

**Comment by simevidas** [comment]
I tried `secure: true` with this:

```js
// initialize a MongoDB store for tokens
passwordless.init(
    new MongoStore(process.env.MONGODB_URL, { 
        mongostore: { collection: 'tokens' } // Note: tokens are stored only temporarily
    }), 
    {
        skipForceSessionSave: true
    }
);
```

but I got the same situation with `req.session.passwordless` being undefined (and it starts working again after I remove `secure: true`, I checked). Note that I’m using connect-mongo to store the session, not cookie-session.

It’s possible that my server-side Express code, my hosting provider’s HTTPS setup, or something other unrelated to passwordless is causing this issue, which is why I’ve decided to wait for someone to confirm that `secure: true` works for them :)

**Comment by NetOperatorWibby** [comment]
@simevidas I got it working! Just follow the first example here https://www.npmjs.com/package/connect-mongodb-session

After repeatedly logging in after changing app code, I no longer have to do so! Thankfully, Mailgun is lightning fast with sending email but still, I'm glad I won't have to deal with that anymore.

**Comment by simevidas** [comment]
Interesting. From what I see, connect-mongodb-session is a drop-in replacement for connect-mongo. Hm, I guess, there’s some weirdness with my server setup.
