### ISSUE TITLE
Possibility to using login token as login code?

### ISSUE THREAD

**Issue by NetOperatorWibby** [florianheinemann/passwordless#95]
![ss 2017-04-05 at 11 38 28 am](https://cloud.githubusercontent.com/assets/1288356/25055676/4115f784-2132-11e7-8842-f07eb6f428ae.png)

The above is an example of what I would *like* to do. Instead of having two tabs open to the same website (one from when user requests login link and another when user clicks link in email), it would be neat if I had an input box where a user could just copy and paste the token to login.

Is this possible?

**Comment by florianheinemann** [comment]
Sure! Just let the form with the text box submit to the URL used to accept tokens. Using GET is the straight forward version that would require no changes at all. Otherwise, you can use the options for acceptToken to allow POST (see https://passwordless.net/docs/Passwordless.html)
