### ISSUE TITLE
How do I use named delivery methods in HTML?

### ISSUE THREAD

**Issue by NetOperatorWibby** [florianheinemann/passwordless#96]
In my server-side code, I have both:

```
passwordless.addDelivery("login", (tokenToSend, uidToSend, recipient, callback) => { ... });
```

and

```
passwordless.addDelivery("new-user", (tokenToSend, uidToSend, recipient, callback) => { ... });
```

How do I differentiate between the two in HTML? Looking at the deep dive, it seems like `<input name="login" type="hidden"/>` and `<input name="new-user" type="hidden"/>` would work but it doesn't.

I have my email sending code wrapped in `if (delivery === "new-user") { ... }` but I'm also not seeing `delivery` in my console logs from my POST routes.

**Comment by florianheinemann** [comment]
The hidden field requires name and value 

Cheers
